version: '3.8'

services:
  selenium-chrome:
    image: selenium/standalone-chrome:latest
    restart: always
    container_name: selenium-chrome
    shm_size: 2gb
    expose:
      - 4444
    networks:
      - service-network

networks:
  service-network:
