version: '3.8'

services:
  selenium-chrome:
    image: selenium/standalone-chrome:latest
    container_name: selenium-chrome
    restart: always
    shm_size: 2gb
    expose:
      - 4444

networks:
  default:
    external: true
    name: l_shared-network