version: '3.8'

services:
  selenium-firefox:
    image: selenium/standalone-firefox:latest
    container_name: selenium-firefox
    restart: always
    shm_size: 2gb
    expose:
      - 4444

networks:
  default:
    external: true
    name: l_shared-network