version: "3.8"

services:
  nginx-gatsby-js:
    restart: always
    image: nginx:latest
    container_name: nginx-gatsby-js
    expose:
      - "80"
    volumes:
      - cache:/var/cache/nginx
      - ${SOURCE_DIR:-./src}:/usr/share/nginx/html:ro
      - ./sites-available/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_EMAIL: ${WEBMASTER_EMAIL}
      VIRTUAL_PORT: "80" # proxy exposed from this port
    networks:
      - auto-reverse-proxy-global-network

volumes:
  cache:

networks:
  auto-reverse-proxy-global-network:
    external: true