version: '3.8'

services:
  swagger-ui:
    restart: always
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - "${HOST_PORT:-8080}:8080"

networks:
  default:
    external: true
    name: l_shared-network