version: '3.8'

services:
  opentsdb:
    image: opentsdb:latest
    restart: always
    container_name: opentsdb
    #  ports:
    #    - "4242:4242"
    expose:
      - "4242"
    environment:
      # read this for config: http://opentsdb.net/docs/build/html/user_guide/configuration.html
      TSDB_ROOT: "/data"
    #      - "TSDB_CORS_ALLOW_ORIGIN=*"
    #      - "TSDB_CORS_ALLOW_METHODS=GET,POST,PUT,DELETE,OPTIONS"
    #      - "TSDB_CORS_ALLOW_HEADERS=Content-Type,Authorization,X-Requested-With,Content-Length,Accept,Origin"
    #      - "TSDB_CORS_ALLOW_CREDENTIALS=true"
    #      - "TSDB_CORS_MAX_AGE=86400"
    #      - "TSDB_CORS_ALLOW_HEADERS=*"
    #      - "TSDB_CORS_ALLOW_METHODS=*"
    #      - "TSDB_USER=opentsdb"
    #      - "TSDB_PASSWORD=opentsdb"
    #      - "TSDB_AUTO_CREATE_METRICS=true"
    #      - "TSDB_AUTO_CREATE_TAGS=true"
    #      - "TSDB_AUTO_CREATE_TAG_KEYS=true"
    #      - "TSDB_AUTO_CREATE_TAG_VALUES=true"
    #      - "TSDB_AUTO_CREATE_TAG_KEYS_TAG_VALUES=true"
    volumes:
      - data:/data
    networks:
      - service-network

volumes:
  data:

networks:
  service-network:
