version: '3.8'

services:
  mysql:
    restart: always
    image: mysql:latest
    container_name: mysql
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE} # optional, the name of a database to be created on image startup
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    expose:
      - 3306
    volumes:
      #      - backup:/docker-entrypoint-initdb.d
      - data:/var/lib/mysql
    networks:
      - service-network

volumes:
  #  backup:
  data:

networks:
  service-network: