version: '3.8'

services:
  minio:
    restart: always
    image: quay.io/minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    expose:
      - "9000" # S3_PORT
      - "9001" # S3_CLI_PORT
#    ports:
    #      - ${S3_PORT}:9000
    #      - ${S3_CLI_PORT}:9001
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_ACCESS_KEY}
      #      S3_ENDPOINT_URL: "http://${S3_HOST}:${S3_PORT}"
      S3_ENDPOINT_URL: "http://minio:9000"
    healthcheck:
      #      test: [ "CMD", "curl", "-f", "http://${S3_HOST}:${S3_PORT}/minio/health/live" ]
      test: [ "CMD", "curl", "-f", "http://minio:9000/minio/health/live" ]
      interval: 60s
      timeout: 20s
      retries: 3
    volumes:
      - s3_data:/data
    networks:
      - service-network

volumes:
  s3_data:

networks:
  service-network:
