version: '3.8'

services:
  chronograf:
    image: chronograf:latest
    container_name: chronograf
    restart: always
    ports:
      - "${HOST_PORT:-8888}:8888"
    volumes:
      - data:/var/lib/chronograf
    environment:
      INFLUXDB_URL: http://influxdb:8086
      INFLUXDB_USERNAME: ${INFLUXDB_USERNAME}
      INFLUXDB_PASSWORD: ${INFLUXDB_PASSWORD}

volumes:
  data:

networks:
  default:
    external: true
    name: l_shared-network