version: '3.8'

services:
  postgres:
    restart: always
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB} # initial database name,  when the image is first started
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    #      POSTGRES_HOST_AUTH_METHOD: "trust" # trust mode (only for dev purposes)
    expose:
      - 5432
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - service-network

volumes:
  data:

networks:
  service-network:
