version: '3.8'

services:
  postgres:
    restart: always
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # POSTGRES_HOST_AUTH_METHOD: "trust" # trust mode (bypass password, only for dev purposes)
      TZ: '${TZ:-Etc/UTC}'
      PGTZ: '${TZ:-Etc/UTC}'
    expose:
      - 5432
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:

networks:
  default:
    external: true
    name: l_shared-network