version: '3.8'

services:
  influxdb:
    restart: always
    # image: quay.io/influxdb/influxdb:v2.0.3
    image: influxdb:latest
    container_name: influxdb
    expose:
      - 8086
    volumes:
      - data:/var/lib/influxdb
    networks:
      - service-network
    environment:
      - INFLUXDB_DB=${INFLUXDB_DB}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}


volumes:
  data:

networks:
  service-network:
    external: true