version: '3.8'

services:
  influxdb:
    restart: always
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "${HOST_PORT:-8086}:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_ORG:-my-org}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_BUCKET:-my-bucket}
    volumes:
      - data:/var/lib/influxdb2
      - config:/etc/influxdb2

volumes:
  data:
  config:

networks:
  default:
    external: true
    name: l_shared-network