version: '3.8'

services:
  influxdb:
    restart: always
    # image: quay.io/influxdb/influxdb:v2.0.3
    image: influxdb:latest
    container_name: influxdb
    expose:
      - 8086
    volumes:
      - data:/var/lib/influxdb
    networks:
      - service-network
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_ORG:-my-org}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_BUCKET:-my-bucket}


volumes:
  data:

networks:
  service-network:
    external: true