version: '3.8'

services:
  redis:
    restart: always
    image: redis
    container_name: redis
    # This one will save a snapshot of the DB every 60 seconds if at least 1 write operation was performed
    command: "redis-server --requirepass ${REDIS_PASSWORD} --maxmemory ${MAX_MEMORY} --maxmemory-policy allkeys-lru --appendonly yes --save 7200 1 --loglevel warning"
    expose:
      - 6379
    volumes:
      - data:/data
      # - redis.conf:/usr/local/etc/redis/redis.conf
      - /etc/localtime:/etc/localtime:ro
    networks:
      - service-network

volumes:
  data:

networks:
  service-network: